services:
  - type: web
    name: watch-time-tester
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    plan: free